apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-02
  labels:
    app: volume-06
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-06
  labels:
    app: volume-06
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volume-06
  template:
    metadata:
      labels:
        app: volume-06
    spec:
      nodeSelector:
        kubernetes.io/hostname: book-worker
      containers:
        - name: example-06
          image: ghcr.io/mmorejon/erase-una-vez-3:v0.2.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: my-volume
              mountPath: /srv/erase-una-vez
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: pv-claim-02
