apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-01
  labels:
    app: volume-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volume-01
  template:
    metadata:
      labels:
        app: volume-01
    spec:
      containers:
        - name: example-01
          image: ghcr.io/mmorejon/erase-una-vez-3:v0.2.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: my-volume
              mountPath: /srv/erase-una-vez
      volumes:
        - name: my-volume
          emptyDir: {}
