apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-env-03
  labels:
    app: cm-03
data:
  CHARACTER: "un palacio."
  SLEEP_TIME: "5s"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-env-03
  labels:
    app: cm-03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cm-03
  template:
    metadata:
      labels:
        app: cm-03
    spec:
      containers:
        - name: container-01
          image: ghcr.io/mmorejon/erase-una-vez-1:v0.3.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: cm-env-03
